### ISSUE TITLE
Source Tree pushing error: 403

### ISSUE THREAD

**Issue by wangpalex** [nus-cs2103-AY2122S1/forum#262] opened 2021-09-21 06:21 UTC
I cloned the tP under my github account using source tree, but it turns out I cannot push to the origin.
I have configured the account in soruce tree as SSH OAuth it worked well for iP....

Below is the error message I get from source tree:
```
git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --tags origin refs/heads/master:refs/heads/master refs/heads/tutorial-adding-command:refs/heads/tutorial-adding-command 
Pushing to https://github.com/wangpeialex/tp.git
remote: Permission to wangpeialex/tp.git denied to wangpeialex.
fatal: unable to access 'https://github.com/wangpeialex/tp.git/': The requested URL returned error: 403
Completed with errors, see above
```

Thanks in advance!

**Comment by NicolasCwy** [comment] 2021-09-21 06:29
Hi can I check what you get when you do, `git remote get-url origin` in your repo? Also try to reclone your repo using `git clone git@github.com:wangpeialex/tp.git`

Not sure if the link in the error log should be https `https://github.com/wangpeialex/tp.git` when you are using ssh.

**Comment by wangpalex** [comment] 2021-09-21 06:33
Hey!
The `git remote get-url origin` returns `https://github.com/wangpeialex/tp.git`
And I have tried reclone a several times before....

**Comment by NicolasCwy** [comment] 2021-09-21 06:34
Hi did you use the command `git clone git@github.com:wangpeialex/tp.git`, and could you try this if you haven't

I did the clone of your repo using ssh and when I did `git remote get-url origin` I got `git@github.com:wangpeialex/tp.git`
Yours seems to be using a https remote

**Comment by wangpalex** [comment] 2021-09-21 06:40
The cloning process using SSH seems to stuck and then failed
```
Cloning into 'tp'...
ssh: connect to host github.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by NicolasCwy** [comment] 2021-09-21 06:43
Hi I am assuming that you tried to a fresh clone of your repo using the SSH command `git clone git@github.com:wangpeialex/tp.git`

Can you try and follow [this guide](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) to make sure that you have configured your SSH for git correctly?

**Comment by wangpalex** [comment] 2021-09-21 06:52
I have put my SSH key into my github account, but the cloning process still stucks...

**Comment by wangpalex** [comment] 2021-09-21 06:54
Sorry I have to deal with some business now, we can resume later.

**Comment by damithc** [comment] 2021-09-21 07:41
@wangpeialex Which OS? I faced a similar problem once (on Windows) and it got resolved after deleting the cached credentials (kept by Windows Credential Manager)

**Comment by wangpalex** [comment] 2021-09-21 07:47
It's MacOS

**Comment by damithc** [comment] 2021-09-21 07:51
> It's MacOS

See if this remedy works https://github.com/trilbymedia/grav-plugin-git-sync/discussions/202#discussioncomment-869515

**Comment by wangpalex** [comment] 2021-09-21 08:20
I have tried to delete all the github credential stored by mac but it still fails to authenticate...

**Comment by damithc** [comment] 2021-09-21 08:54
@wangpeialex are you able to push to any of your GitHub repos? i.e., the problem is specific to the tP fork?

**Comment by wangpalex** [comment] 2021-09-21 08:55
No. I have tried across my other repos, it doesn't work as well. Seems like the git on my laptop is broken....

**Comment by wangpalex** [comment] 2021-09-21 08:59
I feel like it's the problem of SSH because when I run `ssh -T git@github` it's not responding. (I have put the `id_rsa.pub` in my github account)

**Comment by wangpalex** [comment] 2021-09-21 09:14
Ok I figured out what went wrong. It turns out it's the network firewall that is preventing the SSH access. I switched to another network and it works now... Thanks for the help!

**Comment by damithc** [comment] 2021-09-21 09:30
> Ok I figured out what went wrong. It turns out it's the network firewall that is preventing the SSH access. I switched to another network and it works now... Thanks for the help!

Good to hear that @wangpeialex You can go ahead and close this issue.
Thanks for pitching in @NicolasCwy

**Closed as completed** 2021-09-21 09:40 UTC
Labels: type-HelpRequest :sos:
