### ISSUE TITLE
Unable to recognize tags.

### ISSUE THREAD

**Issue by HangZelin** [nus-cs2103-AY2122S1/forum#51] opened 2021-08-20 11:52 UTC
Hey guys. I've encountered the issue that Ip dashboard cannot recognize my tag. I have all my tags in my own Ip. The only thing that I am not sure is that I have amended something for my history commit and repushed the tag, thus some of my previous tags have such notice.

And there is no typo for my tags. 
![image](https://user-images.githubusercontent.com/69517383/130228949-ec517cd5-fee6-48e9-b84d-bf96f81efaa1.png)

Anyone knows what causes this and is there any ways to cope with this issue?

Thanks so much.

**Comment by damithc** [comment] 2021-08-20 12:26
@HangZelin I think you need to share why this tag wasn't detected (i.e., the GitHub screenshot I sent you) -- because that's the problem you need to fix to get the dashboard to recognize this tag.

**Comment by damithc** [comment] 2021-08-22 05:12
@HangZelin is this issue resolved? If yes, please share the solution and close the issue.

**Comment by marcusleeeugene** [comment] 2021-08-25 01:33
> Hey guys. I've encountered the issue that Ip dashboard cannot recognize my tag. I have all my tags in my own Ip. The only thing that I am not sure is that I have amended something for my history commit and repushed the tag, thus some of my previous tags have such notice.
> 
> And there is no typo for my tags.
> ![image](https://user-images.githubusercontent.com/69517383/130228949-ec517cd5-fee6-48e9-b84d-bf96f81efaa1.png)
> 
> Anyone knows what causes this and is there any ways to cope with this issue?
> 
> Thanks so much.

Hi @HangZelin , I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). It seems like the issue is solved, do remember to close it.

![Screenshot 2021-08-25 at 9 27 24 AM](https://user-images.githubusercontent.com/19762656/130711154-54eff15c-f66c-4c42-87cb-04dc58b66ed0.png)

As a note for anyone, once you tagged your project and pushed it to your repo, do visit your github repo page, select on the "Tag" button and double check if the tags you pushed are created successfully. From my experience, the tags on the dashboard will be updated past midnight on the day of your push, so it will take sometime for changes to be reflected.

**Comment by Diwu-Yi** [comment] 2021-08-25 08:49
Hi, @HangZelin , I am also from a senior batch. Since the issue is resolved and explained, it is a good time to **close** this issue now!

**Closed** 2021-08-30 03:37 UTC
Labels: type-HelpRequest :sos:
